### ISSUE TITLE
pilot wrapper cause python yampl bindings to fail with Raythena event service jobs. 

### ISSUE THREAD

**Issue by dougbenjamin** [PanDAWMS/pilot-wrapper#6]
https://github.com/PanDAWMS/pilot-wrapper/blob/306d733ba078c0cb2cded34cadd500d1879b4481/runpilot2-wrapper.sh#L94-L99

  if [ -z "$ATLAS_LOCAL_ROOT_BASE" ]; then
      export ATLAS_LOCAL_ROOT_BASE="/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase"
  fi
  export ALRB_LOCAL_PY3="YES"
  source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
  lsetup "python pilot-testing"

These line cause problems when python is setup outside of the wrapper and python yampl binding are compiled with a version of python 3 that is not from ALRB. 

Why are these lines needed. The wrapper should be able to turn them off.

**Comment by ptrlv** [comment]
Hi Doug, thanks for raising these. For this issue we want the general grid production to setup python3 from ALRB by default and for other cases we can add a switch, say --localpy. Sound ok for you?

**Comment by dougbenjamin** [comment]
yes switch would be perfect.

**Comment by ptrlv** [comment]
You can use --localpy but also need -3 option to select python3. The -3 option will be default once the pilot switch to python3 is deployed.
