### ISSUE TITLE
specify which particular proxy check to skip

### ISSUE THREAD

**Issue by rptaylor** [PanDAWMS/pilot-wrapper#9]
Hi @ptrlv    :)

We are facing an issue that prevents arcproxy -I from working in our environment, while OTOH voms-proxy-info works fine.
Details:
https://ggus.eu/index.php?mode=ticket_info&ticket_id=152002
https://github.com/kubernetes/kubernetes/issues/81089

https://github.com/PanDAWMS/pilot-wrapper/blob/master/runpilot2-wrapper.sh#L141

I wonder if we might have an option in the pilot wrapper that allows us to skip arcproxy while still running voms-proxy-info checks?

Not sure if it would be possible for `-t  <arg>` to accept an optional argument, which could be say `arcproxy` or `voms-proxy-info` in which case that specific check would be skipped, otherwise by default `-t` would skip both?

**Comment by ptrlv** [comment]
Hello Ryan! Accepting an option for -t would require updating harvesters/aCT so best avoided. By default voms-proxy-info is tried first and if working it should not attempt arcproxy. Are you seeing differently?

The jobs I checked are using -t which is a good idea for k8, since unlike grid, it's a well-defined environment (!).

Cheers,
Peter

**Comment by rptaylor** [comment]
@ptrlv Yes you are right, I should have looked closer, it looks like arcproxy will only be tried if voms-proxy-info fails.
So in that case I am not sure of the precise issue that @fbarreir encountered , since it should have worked via voms-proxy-info and we should not be running into this arcproxy issue.

Oh, are you saying you think it is a good idea to use -t to skip proxy checks on k8s?  Why is that?
It's quite useful to have the proxy info output recorded in the job logs, especially debugging proxy related job issues.

Thanks!

**Comment by fbarreir** [comment]
Hi,

The failing arcproxy check is done by the pilot, not the wrapper. From memory I think there was indeed a successful wrapper voms-proxy before the arcproxy check failed.

From a quick search on the pilot:
https://github.com/PanDAWMS/pilot2/blob/d9730778084568dfa8196f9d0acfb5122e94f0b4/pilot/user/atlas/proxy.py#L53
```
# first try to use arcproxy since voms-proxy-info is not working properly on SL6    
#  (memory issues on queues with limited memory)
```

Regards,
Fernando

**Comment by ptrlv** [comment]
@rptaylor I only say skip checks for k8 because the environment is guaranteed to be correct (once commissioned). Anyway, no changes to wrapper in this case so will close issue. Shout if you need other changes.

Cheers,
Peter
